server:
  port: 8083
spring:
  application:
    name: ToDoLabApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/lab_projetos
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect