server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update


  rabbitmq:
    host: localhost
    port: 5672
    username: soegwime
    password: f9yKtPQ4HHGoyK7OzKlidBl83wZJfxkx
    virtualhost: soegwime
    addresses: amqps://soegwime:f9yKtPQ4HHGoyK7OzKlidBl83wZJfxkx@jaragua.lmq.cloudamqp.com/soegwime
  ssl:
    enabled: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: keverson.teodoro@youxlab.com.br
    password: ihqk yhxo wfqu rbkb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


broker:
  queue:
    email:
      name: default.emailMs


